Repository laminas/laminas-stratigility, pull requests merged in 2024-07, with the labels that each got.

#54 Type inference improvements, baseline reduction
  composer.json
  composer.lock
  psalm-baseline.xml
  src/Handler/NotFoundHandler.php
  src/Middleware/NotFoundHandler.php
  src/MiddlewarePipe.php
  src/Next.php
  test/Exception/ExceptionTest.php
  test/Middleware/HostMiddlewareDecoratorTest.php
  test/Middleware/PathMiddlewareDecoratorIntegrationTest.php
  test/Middleware/PathMiddlewareDecoratorTest.php
  test/MiddlewarePipeTest.php
  test/NextTest.php
  test/TestAsset/DelegatingMiddleware.php
  test/TestAsset/ShortCircuitingMiddleware.php
Labels: Enhancement

#56 QA Improvements + 100% Type Coverage for v4
  .gitattributes
  README.md
  docs/book/v4/migration.md
  psalm-baseline.xml
  src/Middleware/DoublePassMiddlewareDecorator.php
  src/Middleware/ErrorHandler.php
  src/Next.php
  test/Middleware/CallableMiddlewareDecoratorTest.php
  test/Middleware/DoublePassMiddlewareDecoratorExceptionTest.php
  test/Middleware/DoublePassMiddlewareDecoratorTest.php
  test/Middleware/ErrorHandlerTest.php
  test/Middleware/HostMiddlewareDecoratorTest.php
Labels: Documentation, Enhancement

#57 Expose the internal middleware queue in `MiddlewarePipe` as an iterable
  src/IterableMiddlewarePipeInterface.php
  src/MiddlewarePipe.php
  test/MiddlewarePipeTest.php
Labels: Enhancement, RFC

#58 Make the v4 docs active.
  docs/book/v4/migration.md
  mkdocs.yml
Labels: Documentation

#59 Allow docs to be built manually
  .github/workflows/docs-build.yml
Labels: Documentation

#61 Update mkdocs.yml navigation and site description
  docs/book/v4/install.md
  docs/book/v4/intro.md
  mkdocs.yml
Labels: Bug, Documentation
